### ISSUE TITLE
challenge fails to load on Firefox and IE

### ISSUE THREAD

**Issue by triune** [GoogleWebComponents/google-recaptcha#5]
TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element.

Above is the error message when clicking "I'm not a robot." in Firefox and IE. The challenge loads fine in Chrome, Safari, and Opera.

**Comment by addyosmani** [comment]
@cbalit do you see this in your upstream repo too?

**Comment by cbalit** [comment]
@addyosmani  yep it seems that it comes from paltform.js on getComputedStyle function

getComputedStyle: function (a, b) {
            return g(),
            l.call(h(this), i(a), b)
        }

No idea why, I'll make some test on monday (i'm in holiday)

**Comment by addyosmani** [comment]
Thanks for verifying, @cbalit. Enjoy your vacation!

**Comment by triune** [comment]
@cbalit is there any chance this will be fixed in the next few weeks? The current state of <re-captcha> being broken in FF and IE prohibits this component's usage in production applications. I'd just like to get an idea of when this will be fixed so as to plan our application's roadmap around it.

**Comment by cbalit** [comment]
@triune i'n not sure to see how to deal with it, since it cames from webcomponents.js and the only available solution is to wrap recaptcha.js file. By the way you sais you made it work by wraping the recaptha api. Even that i didn't suceed. Do you have an exemple of that ?

**Comment by triune** [comment]
@cbalit errantly I thought I had it working because captcha was not presenting a challenge question in FF or IE, just a checkbox for completion; our application worked. However, further testing revealed that wrapping the code did not solve the problem at all. At this point we have to add a major hack to our code to disable recaptcha in the user registration process for IE and FF users until an alternate workaround can be devised or a webcomponents fix because we cannot simply remove Polymer (the other solution).

**Comment by triune** [comment]
This issue seems to have been resolved with Polymer 1.0.0 and google-recaptcha 1.0.0

**Comment by jab** [comment]
Just tested the demos on http://cbalit.github.io/re-captcha/components/re-captcha/ in latest Firefox (41.0.1) on OS X 10.10.5 and it worked, fwiw. (First few times it believed I'm not a robot without making me solve the puzzle but when it finally asked me to it worked.)

**Comment by fearphage** [comment]
So this is still broken in (webcomponentsjs 0.7.x) pre-Polymer 1.0? I can't find a working version myself.

**Comment by cbalit** [comment]
@jab the re-captcha component can validate only by clicking the checkbox. You can find some informations on it here : http://qnimate.com/how-does-googles-no-captcha-recaptcha-work/

**Comment by jab** [comment]
@cbalit I know, all I was saying is that I tested both the case where it doesn't ask you to solve the puzzle, and the case where it does, and both cases worked in Firefox for me.

**Comment by cbalit** [comment]
@jab my misunderstanding. Happy to see that it's working
